C=gcc
LDFLAGS= -lm
CFLAGS=-Wall -Werror -pedantic -std=gnu99 
SOURCES=triangle.c
OBJECTS:=$(SOURCES:.c=.o)
EXECUTABLE=tri

tri: triangle.o
	$(CC) $(LDFLAGS) triangle.o -o tri

triangle.o: triangle.c

clean:
	rm *.o $(EXECUTABLE)
